name: Lint Markdown with proselint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  proselint:
    name: proselint Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install proselint
        run: |
          python -m pip install --upgrade pip
          pip install proselint

      - name: Find tracked Markdown files & run proselint
        shell: bash
        run: |
          set -euo pipefail
          rc=0
          # Iterate tracked .md files (handles spaces/newlines in filenames)
          while IFS= read -r -d '' file; do
            echo "== Linting: $file =="
            # you can add --compact or --json if desired
            if ! proselint --compact "$file"; then
              rc=1
            fi
          done < <(git ls-files -z '*.md')
          if [ "$rc" -ne 0 ]; then
            echo "::error::proselint found issues in one or more Markdown files."
            exit 1
          fi
